name: Maven Build

# Trigger workflow on push and pull requests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # You can use 'zulu', 'adopt', etc.
          java-version: '17'      # Replace with your required Java version (e.g., 8, 11, 17)

      # Cache Maven dependencies for faster builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven commands
      - name: Build with Maven
        run: mvn clean install
